-- MySQL Script generated by MySQL Workbench
-- Ne  7. apríl 2024, 19:29:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Konferencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Konferencia` (
  `idKonferencia` INT NOT NULL AUTO_INCREMENT,
  `Názov` VARCHAR(45) NOT NULL,
  `Dátum_konania` DATE NOT NULL,
  `Stav_konferencie` TINYINT NULL,
  PRIMARY KEY (`idKonferencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stage` (
  `idStage` INT NOT NULL AUTO_INCREMENT,
  `Názov` VARCHAR(45) NULL,
  PRIMARY KEY (`idStage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stage_has_Konferencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stage_has_Konferencia` (
  `idBridge` INT NOT NULL AUTO_INCREMENT,
  `idStage` INT NOT NULL,
  `idKonferencia` INT NOT NULL,
  INDEX `fk_Stage_has_Konferencia_Konferencia1_idx` (`idKonferencia` ASC) VISIBLE,
  INDEX `fk_Stage_has_Konferencia_Stage_idx` (`idStage` ASC) VISIBLE,
  PRIMARY KEY (`idBridge`),
  CONSTRAINT `fk_Stage_has_Konferencia_Stage`
    FOREIGN KEY (`idStage`)
    REFERENCES `mydb`.`Stage` (`idStage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stage_has_Konferencia_Konferencia1`
    FOREIGN KEY (`idKonferencia`)
    REFERENCES `mydb`.`Konferencia` (`idKonferencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prednáška`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prednáška` (
  `idPrednáška` INT NOT NULL AUTO_INCREMENT,
  `Názov` VARCHAR(45) NULL,
  `Krátky_opis` TEXT NULL,
  `Dlhý_opis` TEXT NULL,
  `Max_kapacita` VARCHAR(45) NULL,
  PRIMARY KEY (`idPrednáška`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Priezvisko`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Priezvisko` (
  `idPriezvisko` INT NOT NULL AUTO_INCREMENT,
  `Priezvisko` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPriezvisko`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Meno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Meno` (
  `idMeno` INT NOT NULL AUTO_INCREMENT,
  `Meno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMeno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Osoba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Osoba` (
  `idOsoba` INT NOT NULL AUTO_INCREMENT,
  `Priezvisko_idPriezvisko` INT NOT NULL,
  `Meno_idMeno` INT NOT NULL,
  `Krátky_opis` TEXT NULL,
  `Dlhý_opis` TEXT NULL,
  `Konferencia_idKonferencia` INT NOT NULL,
  `Email` VARCHAR(50) NULL,
  PRIMARY KEY (`idOsoba`),
  INDEX `fk_Osoba_Priezvisko1_idx` (`Priezvisko_idPriezvisko` ASC) VISIBLE,
  INDEX `fk_Osoba_Meno1_idx` (`Meno_idMeno` ASC) VISIBLE,
  INDEX `fk_Osoba_Konferencia1_idx` (`Konferencia_idKonferencia` ASC) VISIBLE,
  CONSTRAINT `fk_Osoba_Priezvisko1`
    FOREIGN KEY (`Priezvisko_idPriezvisko`)
    REFERENCES `mydb`.`Priezvisko` (`idPriezvisko`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Osoba_Meno1`
    FOREIGN KEY (`Meno_idMeno`)
    REFERENCES `mydb`.`Meno` (`idMeno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Osoba_Konferencia1`
    FOREIGN KEY (`Konferencia_idKonferencia`)
    REFERENCES `mydb`.`Konferencia` (`idKonferencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Časové_okná`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Časové_okná` (
  `idČasové_okná` INT NOT NULL AUTO_INCREMENT,
  `Čas_OD` TIME NULL,
  `Čas_DO` TIME NULL,
  `Prednáška_idPrednáška` INT NULL,
  PRIMARY KEY (`idČasové_okná`),
  INDEX `fk_Časové_okná_Prednáška1_idx` (`Prednáška_idPrednáška` ASC) VISIBLE,
  CONSTRAINT `fk_Časové_okná_Prednáška1`
    FOREIGN KEY (`Prednáška_idPrednáška`)
    REFERENCES `mydb`.`Prednáška` (`idPrednáška`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Časové_okná_has_Stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Časové_okná_has_Stage` (
  `idBridge` INT NOT NULL AUTO_INCREMENT,
  `idČasové_okná` INT NOT NULL,
  `dStage` INT NOT NULL,
  INDEX `fk_Časové_okná_has_Stage_Stage1_idx` (`dStage` ASC) VISIBLE,
  INDEX `fk_Časové_okná_has_Stage_Časové_okná1_idx` (`idČasové_okná` ASC) VISIBLE,
  PRIMARY KEY (`idBridge`),
  CONSTRAINT `fk_Časové_okná_has_Stage_Časové_okná1`
    FOREIGN KEY (`idČasové_okná`)
    REFERENCES `mydb`.`Časové_okná` (`idČasové_okná`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Časové_okná_has_Stage_Stage1`
    FOREIGN KEY (`dStage`)
    REFERENCES `mydb`.`Stage` (`idStage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pozícia_vrámci_konferencie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pozícia_vrámci_konferencie` (
  `idPozícia_vrámci_konferencie` INT NOT NULL AUTO_INCREMENT,
  `Pozícia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPozícia_vrámci_konferencie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pozícia_funkcia-RL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pozícia_funkcia-RL` (
  `idPozícia_funkcia-RL` INT NOT NULL AUTO_INCREMENT,
  `Názov` VARCHAR(100) NULL,
  PRIMARY KEY (`idPozícia_funkcia-RL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pozícia_funkcia-RL_has_Osoba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pozícia_funkcia-RL_has_Osoba` (
  `idBridge` INT NOT NULL AUTO_INCREMENT,
  `idPozícia_funkcia-RL` INT NOT NULL,
  `idOsoba` INT NOT NULL,
  INDEX `fk_Pozícia_funkcia-RL_has_Osoba_Osoba1_idx` (`idOsoba` ASC) VISIBLE,
  INDEX `fk_Pozícia_funkcia-RL_has_Osoba_Pozícia_funkcia-RL1_idx` (`idPozícia_funkcia-RL` ASC) VISIBLE,
  PRIMARY KEY (`idBridge`),
  CONSTRAINT `fk_Pozícia_funkcia-RL_has_Osoba_Pozícia_funkcia-RL1`
    FOREIGN KEY (`idPozícia_funkcia-RL`)
    REFERENCES `mydb`.`Pozícia_funkcia-RL` (`idPozícia_funkcia-RL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pozícia_funkcia-RL_has_Osoba_Osoba1`
    FOREIGN KEY (`idOsoba`)
    REFERENCES `mydb`.`Osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Spoločnosť_Firma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Spoločnosť_Firma` (
  `idSpoločnosť_Firma` INT NOT NULL AUTO_INCREMENT,
  `Názov` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSpoločnosť_Firma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Spoločnosť_Firma_has_Osoba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Spoločnosť_Firma_has_Osoba` (
  `idBridge` INT NOT NULL AUTO_INCREMENT,
  `idSpoločnosť_Firma` INT NOT NULL,
  `idOsoba` INT NOT NULL,
  INDEX `fk_Spoločnosť_Firma_has_Osoba_Osoba1_idx` (`idOsoba` ASC) VISIBLE,
  INDEX `fk_Spoločnosť_Firma_has_Osoba_Spoločnosť_Firma1_idx` (`idSpoločnosť_Firma` ASC) VISIBLE,
  PRIMARY KEY (`idBridge`),
  CONSTRAINT `fk_Spoločnosť_Firma_has_Osoba_Spoločnosť_Firma1`
    FOREIGN KEY (`idSpoločnosť_Firma`)
    REFERENCES `mydb`.`Spoločnosť_Firma` (`idSpoločnosť_Firma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Spoločnosť_Firma_has_Osoba_Osoba1`
    FOREIGN KEY (`idOsoba`)
    REFERENCES `mydb`.`Osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Images` (
  `idImages` INT NOT NULL AUTO_INCREMENT,
  `Názov` TEXT NULL,
  `Cesta_k_obrázku` TEXT NULL,
  `ALT` TEXT NULL,
  PRIMARY KEY (`idImages`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Osoba_has_Images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Osoba_has_Images` (
  `idBridge` INT NOT NULL AUTO_INCREMENT,
  `idOsoba` INT NOT NULL,
  `idImages` INT NOT NULL,
  INDEX `fk_Osoba_has_Images_Images1_idx` (`idImages` ASC) VISIBLE,
  INDEX `fk_Osoba_has_Images_Osoba1_idx` (`idOsoba` ASC) VISIBLE,
  PRIMARY KEY (`idBridge`),
  CONSTRAINT `fk_Osoba_has_Images_Osoba1`
    FOREIGN KEY (`idOsoba`)
    REFERENCES `mydb`.`Osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Osoba_has_Images_Images1`
    FOREIGN KEY (`idImages`)
    REFERENCES `mydb`.`Images` (`idImages`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sociálne_siete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sociálne_siete` (
  `idSociálne_siete` INT NOT NULL AUTO_INCREMENT,
  `Názov` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSociálne_siete`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sociálne_siete_osoby`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sociálne_siete_osoby` (
  `idSociálne_siete_osoby` INT NOT NULL AUTO_INCREMENT,
  `Sociálne_siete_idSociálne_siete` INT NOT NULL,
  `Účet` VARCHAR(45) NULL,
  PRIMARY KEY (`idSociálne_siete_osoby`),
  INDEX `fk_Sociálne_siete_osoby_Sociálne_siete1_idx` (`Sociálne_siete_idSociálne_siete` ASC) VISIBLE,
  CONSTRAINT `fk_Sociálne_siete_osoby_Sociálne_siete1`
    FOREIGN KEY (`Sociálne_siete_idSociálne_siete`)
    REFERENCES `mydb`.`Sociálne_siete` (`idSociálne_siete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Osoba_has_Sociálne_siete_osoby`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Osoba_has_Sociálne_siete_osoby` (
  `idBridge` INT NOT NULL AUTO_INCREMENT,
  `idOsoba` INT NOT NULL,
  `idSociálne_siete_osoby` INT NOT NULL,
  INDEX `fk_Osoba_has_Sociálne_siete_osoby_Sociálne_siete_osoby1_idx` (`idSociálne_siete_osoby` ASC) VISIBLE,
  INDEX `fk_Osoba_has_Sociálne_siete_osoby_Osoba1_idx` (`idOsoba` ASC) VISIBLE,
  PRIMARY KEY (`idBridge`),
  CONSTRAINT `fk_Osoba_has_Sociálne_siete_osoby_Osoba1`
    FOREIGN KEY (`idOsoba`)
    REFERENCES `mydb`.`Osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Osoba_has_Sociálne_siete_osoby_Sociálne_siete_osoby1`
    FOREIGN KEY (`idSociálne_siete_osoby`)
    REFERENCES `mydb`.`Sociálne_siete_osoby` (`idSociálne_siete_osoby`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Galéria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Galéria` (
  `idGaléria` INT NOT NULL AUTO_INCREMENT,
  `Konferencia_idKonferencia` INT NOT NULL,
  PRIMARY KEY (`idGaléria`),
  INDEX `fk_Galéria_Konferencia1_idx` (`Konferencia_idKonferencia` ASC) VISIBLE,
  CONSTRAINT `fk_Galéria_Konferencia1`
    FOREIGN KEY (`Konferencia_idKonferencia`)
    REFERENCES `mydb`.`Konferencia` (`idKonferencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Images_has_Galéria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Images_has_Galéria` (
  `idBridge` INT NOT NULL AUTO_INCREMENT,
  `idImages` INT NOT NULL,
  `idGaléria` INT NOT NULL,
  INDEX `fk_Images_has_Galéria_Galéria1_idx` (`idGaléria` ASC) VISIBLE,
  INDEX `fk_Images_has_Galéria_Images1_idx` (`idImages` ASC) VISIBLE,
  PRIMARY KEY (`idBridge`),
  CONSTRAINT `fk_Images_has_Galéria_Images1`
    FOREIGN KEY (`idImages`)
    REFERENCES `mydb`.`Images` (`idImages`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Images_has_Galéria_Galéria1`
    FOREIGN KEY (`idGaléria`)
    REFERENCES `mydb`.`Galéria` (`idGaléria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sponzor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sponzor` (
  `idSponzor` INT NOT NULL AUTO_INCREMENT,
  `Názov_sponzora` VARCHAR(45) NULL,
  `Konferencia_idKonferencia` INT NOT NULL,
  PRIMARY KEY (`idSponzor`),
  INDEX `fk_Sponzor_Konferencia1_idx` (`Konferencia_idKonferencia` ASC) VISIBLE,
  CONSTRAINT `fk_Sponzor_Konferencia1`
    FOREIGN KEY (`Konferencia_idKonferencia`)
    REFERENCES `mydb`.`Konferencia` (`idKonferencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sponzor_has_Sociálne_siete_osoby`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sponzor_has_Sociálne_siete_osoby` (
  `idBridge` INT NOT NULL AUTO_INCREMENT,
  `idSponzor` INT NOT NULL,
  `idSociálne_siete_osoby` INT NOT NULL,
  INDEX `fk_Sponzor_has_Sociálne_siete_osoby_Sociálne_siete_osoby1_idx` (`idSociálne_siete_osoby` ASC) VISIBLE,
  INDEX `fk_Sponzor_has_Sociálne_siete_osoby_Sponzor1_idx` (`idSponzor` ASC) VISIBLE,
  PRIMARY KEY (`idBridge`),
  CONSTRAINT `fk_Sponzor_has_Sociálne_siete_osoby_Sponzor1`
    FOREIGN KEY (`idSponzor`)
    REFERENCES `mydb`.`Sponzor` (`idSponzor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sponzor_has_Sociálne_siete_osoby_Sociálne_siete_osoby1`
    FOREIGN KEY (`idSociálne_siete_osoby`)
    REFERENCES `mydb`.`Sociálne_siete_osoby` (`idSociálne_siete_osoby`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Register` (
  `idRegister` INT NOT NULL AUTO_INCREMENT,
  `idKonferencia` INT NOT NULL,
  `idPozícia_vrámci_konferencie` INT NOT NULL,
  PRIMARY KEY (`idRegister`),
  INDEX `fk_Register_Konferencia1_idx` (`idKonferencia` ASC) VISIBLE,
  INDEX `fk_Register_Pozícia_vrámci_konferencie1_idx` (`idPozícia_vrámci_konferencie` ASC) VISIBLE,
  CONSTRAINT `fk_Register_Konferencia1`
    FOREIGN KEY (`idKonferencia`)
    REFERENCES `mydb`.`Konferencia` (`idKonferencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Register_Pozícia_vrámci_konferencie1`
    FOREIGN KEY (`idPozícia_vrámci_konferencie`)
    REFERENCES `mydb`.`Pozícia_vrámci_konferencie` (`idPozícia_vrámci_konferencie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Register_has_Osoba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Register_has_Osoba` (
  `idBridge` INT NOT NULL AUTO_INCREMENT,
  `idRegister` INT NOT NULL,
  `idOsoba` INT NOT NULL,
  INDEX `fk_Register_has_Osoba_Osoba1_idx` (`idOsoba` ASC) VISIBLE,
  INDEX `fk_Register_has_Osoba_Register1_idx` (`idRegister` ASC) VISIBLE,
  PRIMARY KEY (`idBridge`),
  CONSTRAINT `fk_Register_has_Osoba_Register1`
    FOREIGN KEY (`idRegister`)
    REFERENCES `mydb`.`Register` (`idRegister`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Register_has_Osoba_Osoba1`
    FOREIGN KEY (`idOsoba`)
    REFERENCES `mydb`.`Osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prednáška_has_Register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prednáška_has_Register` (
  `idBridge` INT NOT NULL AUTO_INCREMENT,
  `idPrednáška` INT NOT NULL,
  `idRegister` INT NOT NULL,
  INDEX `fk_Prednáška_has_Register_Register1_idx` (`idRegister` ASC) VISIBLE,
  INDEX `fk_Prednáška_has_Register_Prednáška1_idx` (`idPrednáška` ASC) VISIBLE,
  PRIMARY KEY (`idBridge`),
  CONSTRAINT `fk_Prednáška_has_Register_Prednáška1`
    FOREIGN KEY (`idPrednáška`)
    REFERENCES `mydb`.`Prednáška` (`idPrednáška`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prednáška_has_Register_Register1`
    FOREIGN KEY (`idRegister`)
    REFERENCES `mydb`.`Register` (`idRegister`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Povedali_o_nás`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Povedali_o_nás` (
  `idPovedali_o_nás` INT NOT NULL AUTO_INCREMENT,
  `Text` TEXT NULL,
  `Osoba_idOsoba` INT NOT NULL,
  PRIMARY KEY (`idPovedali_o_nás`),
  INDEX `fk_Povedali_o_nás_Osoba1_idx` (`Osoba_idOsoba` ASC) VISIBLE,
  CONSTRAINT `fk_Povedali_o_nás_Osoba1`
    FOREIGN KEY (`Osoba_idOsoba`)
    REFERENCES `mydb`.`Osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sponzor_has_Images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sponzor_has_Images` (
  `idBridge` INT NOT NULL AUTO_INCREMENT,
  `idSponzor` INT NOT NULL,
  `idImages` INT NOT NULL,
  INDEX `fk_Sponzor_has_Images_Images1_idx` (`idImages` ASC) VISIBLE,
  INDEX `fk_Sponzor_has_Images_Sponzor1_idx` (`idSponzor` ASC) VISIBLE,
  PRIMARY KEY (`idBridge`),
  CONSTRAINT `fk_Sponzor_has_Images_Sponzor1`
    FOREIGN KEY (`idSponzor`)
    REFERENCES `mydb`.`Sponzor` (`idSponzor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sponzor_has_Images_Images1`
    FOREIGN KEY (`idImages`)
    REFERENCES `mydb`.`Images` (`idImages`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
